/**
 * Reply understanding.
 *
 * Order matters and is not negotiable:
 *
 *   1. DETERMINISTIC RULES FIRST. "stop", "remove me", "do not contact",
 *      "unsubscribe" and out-of-office auto-replies are recognised by plain
 *      regex. Compliance must never depend on a model being available, in
 *      budget, or correct.
 *   2. Only then the fast tier, with a Zod schema, for the shades of interest.
 *
 * And the rule that protects the whole product:
 *
 *   A COMMITMENT REQUIRES EVIDENCE IN THE TEXT. The model's opinion is not
 *   enough. Every commitment type has a deterministic corroboration pattern
 *   that must also match, so "sounds interesting" can never become proof that
 *   a company will pay. intent_score is advisory metadata and gates nothing.
 */
import { getDb } from '../../lib/db';
import { newId } from '../../lib/hash';
import { createLogger } from '../../lib/logger';
import { llmComplete } from '../../lib/llm/index';
import {
  ReplyAnalysis,
  type CommitmentInput,
  type CommitmentType,
  type ReplyClassification,
} from '../../lib/contracts';

const logger = createLogger('outreach:classify');

export interface ClassificationOutcome {
  analysis: ReplyAnalysis;
  /** True when no model was consulted. */
  deterministic: boolean;
  rule: string | null;
}

// --- deterministic rules -----------------------------------------------------

/** Opt-out language. Broad on purpose: a false positive costs one lead. */
export const UNSUBSCRIBE_PATTERN =
  /\b(unsubscribe|remove me|remove us|take me off|take us off|opt[\s-]?out|do not contact|don'?t contact|do not email|don'?t email|stop emailing|no more emails?|delete my (email|address|details)|lose my (email|address))\b/i;

/** A bare "stop" on its own line is an opt-out; "stop by our store" is not. */
export const BARE_STOP_PATTERN = /(^|\n)\s*(stop|unsubscribe|remove)\s*[.!]?\s*($|\n)/i;

export const OUT_OF_OFFICE_PATTERN =
  /\b(out of (the )?office|ooo\b|on (vacation|holiday|leave|annual leave)|away from (my|the) (desk|office)|parental leave|maternity leave|currently unavailable|auto(matic)?[- ]?reply|automatic response|i am currently away|will be back on|returning on)\b/i;

/**
 * Only unambiguous rejections. "We already have X" or "not right now" are
 * deliberately NOT here — those are competitor/timing signals that deserve a
 * real reading rather than a keyword verdict.
 */
export const NOT_INTERESTED_PATTERN =
  /\b(not interested|no thanks|no thank you|we'?re all set|we are all set|not a (good )?fit|not for us|no interest|please stop sending)\b/i;

export const WRONG_PERSON_PATTERN =
  /\b(wrong person|not the right person|no longer (with|at) (the )?(company|us)|has left the company|try (contacting|reaching) )\b/i;

const AUTO_REPLY_HEADERS = ['auto-submitted', 'x-autoreply', 'x-autorespond', 'x-auto-response-suppress', 'precedence'];

function looksAutoGenerated(headers: Record<string, string>): boolean {
  for (const key of AUTO_REPLY_HEADERS) {
    const value = headers[key];
    if (value === undefined) continue;
    const v = value.toLowerCase();
    if (key === 'auto-submitted') {
      if (v !== 'no') return true;
    } else if (key === 'precedence') {
      if (/auto|bulk|junk/.test(v)) return true;
    } else {
      return true;
    }
  }
  return false;
}

function baseAnalysis(classification: ReplyClassification, intent: string): ReplyAnalysis {
  return {
    classification,
    intent,
    requestedFeature: null,
    competitorMentioned: null,
    priceReaction: 'NOT_MENTIONED',
    timing: null,
    explicitlyWantsAccess: false,
    explicitlyAcceptedPrice: false,
    requiresHuman: false,
    intentScore: 0,
  };
}

/**
 * Runs before anything else and without any model. Returns null when the reply
 * needs real interpretation.
 */
export function classifyDeterministic(
  text: string,
  headers: Record<string, string> = {},
): { analysis: ReplyAnalysis; rule: string } | null {
  const body = (text ?? '').slice(0, 20_000);

  if (UNSUBSCRIBE_PATTERN.test(body) || BARE_STOP_PATTERN.test(body)) {
    return {
      analysis: { ...baseAnalysis('UNSUBSCRIBE', 'explicit opt-out request'), requiresHuman: false },
      rule: 'UNSUBSCRIBE_KEYWORD',
    };
  }

  const headerAuto = looksAutoGenerated(normalizeHeaderKeys(headers));
  if (headerAuto || OUT_OF_OFFICE_PATTERN.test(body)) {
    return {
      analysis: baseAnalysis('OUT_OF_OFFICE', 'automated out-of-office reply'),
      rule: headerAuto ? 'AUTO_REPLY_HEADER' : 'OUT_OF_OFFICE_PHRASE',
    };
  }

  if (NOT_INTERESTED_PATTERN.test(body)) {
    return {
      analysis: baseAnalysis('NOT_INTERESTED', 'declined'),
      rule: 'NOT_INTERESTED_KEYWORD',
    };
  }

  if (WRONG_PERSON_PATTERN.test(body)) {
    return { analysis: baseAnalysis('WRONG_PERSON', 'not the right contact'), rule: 'WRONG_PERSON_KEYWORD' };
  }

  return null;
}

export function normalizeHeaderKeys(headers: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(headers ?? {})) out[k.toLowerCase()] = v;
  return out;
}

// --- model-assisted classification ------------------------------------------

const CLASSIFY_SYSTEM = [
  'You classify one reply to a cold outreach email about a product that DOES NOT EXIST YET and is being validated.',
  'Return only the requested fields.',
  'Guidance:',
  '- explicitlyAcceptedPrice is true ONLY if the reply states the stated price is acceptable or that they will pay it.',
  '- explicitlyWantsAccess is true ONLY if the reply asks for the product, an install, a trial, or the pilot.',
  '- Vague positivity ("sounds interesting", "cool idea", "keep me posted") is INTERESTED_WEAK, never strong.',
  '- requiresHuman is true for anything legal, contractual, or that you cannot answer from the offer.',
  '- intentScore is advisory metadata only. It decides nothing.',
].join('\n');

export async function classifyReply(params: {
  text: string;
  subject?: string;
  headers?: Record<string, string>;
  offerSummary?: string;
}): Promise<ClassificationOutcome> {
  const deterministic = classifyDeterministic(params.text, params.headers ?? {});
  if (deterministic) {
    logger.info('reply classified deterministically', { rule: deterministic.rule });
    return { analysis: deterministic.analysis, deterministic: true, rule: deterministic.rule };
  }

  try {
    const res = await llmComplete({
      tier: 'fast',
      task: 'outreach.classify_reply',
      schemaName: 'ReplyAnalysis',
      maxTokens: 800,
      schema: ReplyAnalysis,
      system: CLASSIFY_SYSTEM,
      user: JSON.stringify({
        subject: params.subject ?? '',
        offer: params.offerSummary ?? '',
        reply: (params.text ?? '').slice(0, 6000),
      }),
    });
    // A model may not override an opt-out; that direction is one-way only.
    const analysis = res.data.classification === 'UNSUBSCRIBE'
      ? { ...res.data, requiresHuman: false }
      : res.data;
    return { analysis, deterministic: false, rule: null };
  } catch (err) {
    logger.error('reply classification failed; flagging for a human', { err: String(err) });
    return {
      analysis: { ...baseAnalysis('OTHER', 'classification unavailable'), requiresHuman: true },
      deterministic: false,
      rule: null,
    };
  }
}

// --- commitment extraction ---------------------------------------------------

/**
 * Deterministic corroboration. The model's boolean is necessary but never
 * sufficient: the words have to actually be in the reply.
 */
const COMMITMENT_EVIDENCE: ReadonlyArray<{
  type: CommitmentType;
  pattern: RegExp;
  requires: (a: ReplyAnalysis) => boolean;
}> = [
  {
    type: 'EXPLICIT_PRICE_ACCEPTANCE',
    // Note: no leading \b — the first alternative starts with "$", which is not
    // a word character, so a word boundary there would never match.
    pattern:
      /(\$\s?\d+(\.\d{2})?\s*(\/|per\s)?\s*(mo|month|mo\.)?\s*(is|sounds|seems|works|would be)?\s*(fine|fair|ok|okay|reasonable|great|good|worth it|no problem|acceptable)\b)|\b((happy|willing|glad) to pay|we'?ll pay|i'?ll pay|(that|the|your) price (is|works|sounds) (fine|fair|ok|okay|good|reasonable|right)|worth (it|that) (at|for)|sign me up at|take my money)\b/i,
    requires: (a) => a.explicitlyAcceptedPrice && a.priceReaction === 'ACCEPTED',
  },
  {
    type: 'INSTALL_REQUEST',
    pattern: /\b(send (me|us) the install|install (it|the app)|add it to (my|our) store|when can (i|we) install|i'?ll install|we'?ll install|get me the app)\b/i,
    requires: (a) => a.explicitlyWantsAccess,
  },
  {
    type: 'TRIAL_REQUEST',
    pattern: /\b((start|begin|set up|sign (me|us) up for) a (trial|test)|(we|i) (would|'?d) (like|love) to (try|test)|put (me|us) (on|in) the beta|early access)\b/i,
    requires: (a) => a.explicitlyWantsAccess,
  },
  {
    type: 'PILOT_SIGNUP',
    pattern: /\b(join the pilot|(we|i) want (in on |in on|in for )?the pilot|count (me|us) in|sign (me|us) up|reserve (me|us|a spot|one)|first install|(we|i)'?(d| would) like (a|one of the) (pilot|first) )\b/i,
    requires: (a) => a.explicitlyWantsAccess,
  },
  {
    type: 'ONBOARDING_DETAILS',
    pattern: /\b([a-z0-9-]+\.myshopify\.com|our store (url|link|is)|store (url|domain) is|here'?s our (store|site|shop))\b/i,
    requires: (a) => a.explicitlyWantsAccess || a.explicitlyAcceptedPrice,
  },
];

/**
 * Which commitments this reply genuinely evidences. Pure function — easy to
 * test, impossible for a prompt to talk around.
 */
export function commitmentTypesFor(analysis: ReplyAnalysis, replyText: string): CommitmentType[] {
  // An opt-out or a rejection can never simultaneously be a commitment.
  const blocked: ReplyClassification[] = ['UNSUBSCRIBE', 'NOT_INTERESTED', 'OUT_OF_OFFICE', 'WRONG_PERSON'];
  if (blocked.includes(analysis.classification)) return [];

  const text = (replyText ?? '').slice(0, 20_000);
  const types: CommitmentType[] = [];
  for (const rule of COMMITMENT_EVIDENCE) {
    if (rule.requires(analysis) && rule.pattern.test(text)) types.push(rule.type);
  }
  return types;
}

/**
 * Writes commitments. `dedupe_key` (campaign + company + type) is a UNIQUE
 * index, so one company can never be counted twice for the same type no matter
 * how many times they reply.
 */
export async function recordCommitments(inputs: CommitmentInput[]): Promise<number> {
  if (inputs.length === 0) return 0;
  const db = await getDb();
  let created = 0;
  for (const input of inputs) {
    const res = await db.query<{ id: string }>(
      `INSERT INTO commitments
         (id, campaign_id, prospect_id, company_key, type, price_monthly, source,
          evidence_text, evidence_url, message_id, verified, dedupe_key)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
       ON CONFLICT (dedupe_key) DO NOTHING
       RETURNING id`,
      [
        newId('cmt'),
        input.campaignId,
        input.prospectId,
        input.companyKey,
        input.type,
        input.priceMonthly,
        input.source,
        input.evidenceText.slice(0, 2000),
        input.evidenceUrl ?? null,
        input.messageId ?? null,
        input.verified ?? false,
        `${input.campaignId}:${input.companyKey}:${input.type}`,
      ],
    );
    if (res.rows[0]?.id) created += 1;
  }
  if (created > 0) logger.info('commitments recorded', { created });
  return created;
}
